name: build-resume
on:
  push:
    branches:
      - main
    paths:
      - 'janpreet-singh-resume.tex'      
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout main
      run: git checkout main

    - name: Run Makefile
      run: |
        make run

    - name: Add & Commit
      if: success()
      run: |
        git config --local user.email "janpreetsinghgill@gmail.com"
        git config --local user.name "Janpreet Singh via GitHub Action"
        date > time.txt
        git add janpreet-singh-resume.pdf time.txt
        git commit -m "🤖 resume-building bot is helping"

    - name: Push to main
      if: success()
      run: git push
      
    - name: Push to Personal Website Repo
      run: |
          rm -rf vigilant-dollop
          git config --global user.email "janpreetsinghgill@gmail.com"
          git config --global user.name "Janpreet Singh"
          git clone https://janpreet:${{ secrets.PAT }}@github.com/janpreet/vigilant-dollop.git
          cp janpreet-singh-resume.pdf vigilant-dollop/janpreet-singh-resume.pdf
          cd vigilant-dollop/
          git add janpreet-singh-resume.pdf
          git commit -m "🤖 resume-building bot is helping"
          git push --set-upstream origin main
          cd ..
          rm -rf vigilant-dollop
